name: Bug Report
description: Report a bug or unexpected behavior
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        **README: Before You Submit Your Issue**
        - Issues are not a place to ask support questions or discussions. Please ask any questions or discussions on the [Matrix Channel](https://matrix.to/#/#yattee:matrix.org) or [discussions page](https://github.com/yattee/yattee/discussions).
        - Also check the [Wiki](https://github.com/yattee/yattee/wiki) for any information or FAQs that help you with yattee.
        
  - type: checkboxes
    attributes:
      label: Guidelines
      description: Please ensure you've completed all of the following.
      options:
        - label: I have searched the [issue tracker](https://github.com/yattee/yattee/issues) for a bug report but haven't found the one that I'm opening for.
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: Tell us what happened and the steps you have done to encounter this bug if possible in clear description?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Tell us what you expected to happen in clear description?
    validations:
      required: true

  - type: input
    attributes:
      label: Device & OS Version
      description: What Device and version are you running?
      placeholder: e.g. iPhone (iOS 15.5)
    validations:
      required: true

  - type: input
    attributes:
      label: App Version
      description: What version are you running?
      placeholder: e.g. 1.4
    validations:
      required: true

  - type: dropdown
    attributes:
      label: App Installation Method
      options:
        - TestFlight
        - ipa (GitHub Releases)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash log
      description: Submit your crash log if available
      placeholder: |
          1. Go to 'Settings'
          2. Click on 'Privacy'
          3. Scroll down and open 'Analytics & Improvements'
          4. Go to 'Analytics Data'
          4. See crash log
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots or Videos
      description: If possible, submit your screenshots or a video of the bug that you have encountered to better understanding
    validations:
      required: false
